### ISSUE TITLE
JSON dump fails on Windows

### ISSUE THREAD

**Issue by skylord123** [koodaamo/tnefparse#52]
I tried doing a JSON dump and I got this error:
```
PS C:\Users\REMOVED\Downloads\test> tnefparse ./winmail.dat -d -l INFO
INFO:tnef-decode:Skipping checksum for performance
Traceback (most recent call last):
  File "C:\Users\REMOVED\AppData\Local\Programs\Python\Python37-32\Scripts\tnefparse-script.py", line 11, in <module>
    load_entry_point('tnefparse', 'console_scripts', 'tnefparse')()
  File "c:\users\REMOVED\projects\tnefparse\tnefparse\cmdline.py", line 89, in tnefparse
    print(json.dumps(t.dump(force_strings=True), sort_keys=True, indent=4))
  File "c:\users\REMOVED\projects\tnefparse\tnefparse\tnef.py", line 358, in dump
    attachment[att.name_str] = get_data(att)
  File "c:\users\REMOVED\projects\tnefparse\tnefparse\tnef.py", line 342, in get_data
    if force_strings and isinstance(a.data, bytes):
  File "c:\users\REMOVED\projects\tnefparse\tnefparse\mapi.py", line 205, in data
    return systime(self.raw_data)
  File "c:\users\REMOVED\projects\tnefparse\tnefparse\util.py", line 48, in systime
    return datetime.utcfromtimestamp((ft - EPOCH_AS_FILETIME) / HUNDREDS_OF_NANOSECONDS)
OSError: [Errno 22] Invalid argument
```

I did a debug of the `ft`, `EPOCH_AS_FILETIME`, and `HUNDREDS_OF_NANOSECONDS` variables as well as the end result and here is the output:

```
PS C:\Users\REMOVED\Downloads\test> tnefparse ./winmail.dat -d -l DEBUG
INFO:tnef-decode:Skipping checksum for performance
DEBUG:tnef-decode:ft: 915151392000000000
DEBUG:tnef-decode:EPOCH_AS_FILETIME: 116444736000000000
DEBUG:tnef-decode:HUNDREDS_OF_NANOSECONDS: 10000000
DEBUG:tnef-decode:END RESULT: 79870665600.0
Traceback (most recent call last):
  File "C:\Users\REMOVED\AppData\Local\Programs\Python\Python37-32\Scripts\tnefparse-script.py", line 11, in <module>
    load_entry_point('tnefparse', 'console_scripts', 'tnefparse')()
  File "c:\users\REMOVED\projects\tnefparse\tnefparse\cmdline.py", line 89, in tnefparse
    print(json.dumps(t.dump(force_strings=True), sort_keys=True, indent=4))
  File "c:\users\REMOVED\projects\tnefparse\tnefparse\tnef.py", line 358, in dump
    attachment[att.name_str] = get_data(att)
  File "c:\users\REMOVED\projects\tnefparse\tnefparse\tnef.py", line 342, in get_data
    if force_strings and isinstance(a.data, bytes):
  File "c:\users\REMOVED\projects\tnefparse\tnefparse\mapi.py", line 205, in data
    return systime(self.raw_data)
  File "c:\users\REMOVED\projects\tnefparse\tnefparse\util.py", line 48, in systime
    return datetime.utcfromtimestamp((ft - EPOCH_AS_FILETIME) / HUNDREDS_OF_NANOSECONDS)
OSError: [Errno 22] Invalid argument
```

So it looks like the `datetime.utcfromtimestamp` function can't take the value of `79870665600.0` which I was able to confirm on my local terminal:

```
>>> print(datetime.utcfromtimestamp(79870665600.0))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 22] Invalid argument
```

Is the math just being done wrong on Windows? I was able to patch it by changing `HUNDREDS_OF_NANOSECONDS` from `10000000` to `1000000000`. This at least got the function running but I can't confirm that the dates are correct at this time.

Thanks!

**Comment by Beercow** [comment]
Can we get a fix for this. Not sure how you would like to handle it.
Date fields that do not have a value are arbitrarily given a value of 1/1/4501 and therefore cannot be empty.

https://docs.microsoft.com/en-us/previous-versions/office/developer/office-xp/aa155722(v=office.10)#odc_olcustfrm1_chooser

**Comment by petri** [comment]
Thanks. merged.
